# Define the list of text with synonyms
text_with_synonyms = [
    "politeness, respect",
    "politeness, respect",
    "politeness, respect",
    "different, alternative",
    "finding your way, orientation",
    "finding your way, orientation",
    "finding your way, orientation",
    "verification, validation, approval",
    "account, briefing",
    "objective, target",
    "importance, top priority",
    "question, query",
    "account, briefing",
    "account, briefing",
    "question, query",
    "verification, validation, approval",
    "verification, validation, approval",
    "verification, validation, approval",
    "ask, petition",
    "show feelings, communicate emotions",
    "collaboration, cooperation",
    "account, briefing",
    "verification, validation, approval",
    "finding your way, orientation",
    "ask, petition",
    "account, briefing",
    "question, query",
    "verification, validation, approval",
    "grabbing attention, getting noticed",
    "question, query",
    "fixing, rectifying",
    "fixing, rectifying",
    "clarification, elaboration",
    "clarification, elaboration",
    "verification, validation, approval",
    "verification, validation, approval",
    "clarification, elaboration",
    "clarification, elaboration",
    "verification, validation, approval",
    "question, query",
    "clarification, elaboration",
    "finding your way, orientation",
    "verification, validation, approval",
    "verification, validation, approval",
    "verification, validation, approval",
    "question, query",
    "verification, validation, approval",
    "politeness, respect",
    "politeness, respect",
    "question, query",
    "objective, target",
    "verification, validation, approval",
    "verification, validation, approval",
    "account, briefing",
    "politeness, respect",
    "account, briefing",
    "ask, petition",
    "importance, top priority",
    "account, briefing",
    "account, briefing",
    "account, briefing",
    "ask, petition",
    "account, briefing",
    "finding your way, orientation",
    "verification, validation, approval",
    "verification, validation, approval",
    "verification, validation, approval",
    "account, briefing",
    "objective, target",
    "account, briefing",
    "account, briefing",
    "verification, validation, approval",
    "ask, petition",
    "account, briefing",
    "objective, target",
    "collaboration, cooperation",
    "account, briefing",
    "collaboration, cooperation",
    "account, briefing",
    "collaboration, cooperation",
    "question, query",
    "verification, validation, approval",
    "verify, double-check",
    "verification, validation, approval",
    "account, briefing",
    "account, briefing",
    "verification, validation, approval",
    "collaboration, cooperation",
    "fixing, rectifying",
    "instruction, directive",
    "account, briefing",
    "account, briefing",
    "account, briefing",
    "verify, double-check",
    "account, briefing",
    "different, alternative",
    "collaboration, cooperation",
    "account, briefing",
    "ask, petition",
    "account, briefing",
    "account, briefing",
    "collaboration, cooperation"
]

# Extract only the first word from each item (splitting by commas and taking the first element)
synonyms_only = [item.split(',')[0].strip() for item in text_with_synonyms]

# Print the list of synonyms
print(synonyms_only)
